ci:
  skip: [pip-compile]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - "--check-untyped-defs"
          - "--ignore-missing-imports"
        additional_dependencies:
          - types-setuptools
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args:
          - --resolver=backtracking
          - --generate-hashes
          - requirements/requirements.in
        files: ^requirements/requirements.in$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args:
          - --resolver=backtracking
          - --generate-hashes
          - requirements/requirements-dev.in
        files: ^requirements/requirements-dev.in$
